<?php

$title =  $this->translate('Sign In'); # page title
# meta keywords
$this->headMeta()->appendName('keywords', 'Login, Sign In, Authenticate');
# meta description
$this->headMeta()->appendName('description', 'Inicio de sesión');
# page title
$this->headTitle($this->escapeHtml($title));


#form
$form = $this->form;
$form->setAttribute('action', $this->url('login'));  #oops
$form->prepare();

?>

<div class="container">
	<div class="row">
		<div class="col-md-4 shadow-sm">
			<h3 class="mb-3 pt-2 text-md-center">
				<?= $this->escapeHtml($this->translate('Acceso a usuarios')); ?>
			</h3>

			<?= $this->form()->openTag($form); ?>

			
			<p style="font-size: 20px;">si no cuenta con un usuario, se puede registar <a href="<?= $this->url('signup') ?>">AQUÍ</a></p>
			

			<div class="mb-3">
                <?= $this->formLabel($form->get('email')); ?>
				<div class="form-group">
                   <?= $this->formEmail($form->get('email')); ?>
				</div>
                
                <div class="text-danger">
                	<?= $this->formElementErrors($form->get('email')); ?>
                </div>
			</div>

			<div class="mb-3">
				<div class="form-group">
                   <?= $this->formPassword($form->get('password')); ?>
				</div>
                
                <div class="text-danger">
                	<?= $this->formElementErrors($form->get('password')); ?>
                </div>
			</div>

			<!-- submit button -->
			<div class="mb-3 float-right">
				<?= $this->formHidden($form->get('csrf')); ?>
				<div class="text-danger">
					<?= $this->formElementErrors($form->get('csrf')); ?>
				</div>
				<?= $this->formSubmit($form->get('account_login')); ?>
			</div>

			<?= $this->form()->closeTag(); ?>
		</div>
	</div>
</div>